aplicaciones/www/src/components/Menu.astro, aplicaciones/www/src/datosVisibles/indicadores.ts, aplicaciones/www/src/pages/index.astro
Agregar componente `Menu` con 'YAs' e indicadres y los datos para armarlo.
=> ✨ Agregar menú y datos del menú

aplicaciones/www/src/components/Mapa.astro, aplicaciones/www/src/components/Menu.astro
💄 Arreglar info del lugar mapa quitando municipio en nivel `departamentos` y agregar fuente a css.
=> 💄 Arreglar info lugar mapa y agregar fuente

aplicaciones/www/src/components/Mapa.astro, aplicaciones/www/src/pages/index.astro
Arreglar escala de mapa cuando se actualiza el tamaño de la ventana.
=> ⚡️ Arreglo escala mapa

aplicaciones/www/src/components/Mapa.astro, aplicaciones/www/src/components/MapaDetalle.astro, aplicaciones/www/src/pages/index.astro, aplicaciones/www/src/utilidades/cerebro.ts
Falta luego hacer posible que se muestren varios para comparar.
=> Versión 1 del mapa detalle.

aplicaciones/www/src/componentes/Mapa.astro, aplicaciones/www/src/componentes/MapaDetalle.ts, aplicaciones/www/src/componentes/SelectorNivel.astro, aplicaciones/www/src/pages/index.astro
Agregar menuú desplegable para años e invertir orden de mapa y línea de tiempo
=> ✨ Agregar menuú desplegable años

aplicaciones/www/src/datosVisibles/indicadores.ts
Actualizar  lista de indicadores en el menú según lo que hay hasta ahora.
=> 📝 Actualizar  lista de indicadores en menú

aplicaciones/www/src/componentes/Mapa.astro, aplicaciones/www/src/componentes/Menu.astro, aplicaciones/www/src/componentes/MenuAnios.astro, aplicaciones/www/src/pages/index.astro, aplicaciones/www/src/utilidades/cerebro.ts
Organizar elementos de tablero central e independizar como otro componente el menú de años
=> 🐺 Avances varios

aplicaciones/www/src/componentes/Mapa.astro, aplicaciones/www/src/utilidades/cerebro.ts
Definir el color del mapa según la dirección deseada del indicador.
=> 🐛 Definir dirección indicador

aplicaciones/www/src/componentes/Mapa.astro, aplicaciones/www/src/componentes/MapaDetalle.ts
Pintar mapa detalle del departamento al elegir un municipio en el mapa grande.
=> ✨ Pintar mapa detalle depto al elegir municipio

aplicaciones/www/src/componentes/DescripcionYa.astro, aplicaciones/www/src/componentes/FichaTecnica.astro, aplicaciones/www/src/pages/[ya]/[indicador].astro
Mejora: convertir enlaces en enlaces en ficha técnica
=> 🐛 Convertir enlaces en enlaces en ficha técnica

aplicaciones/www/src/componentes/Linea.ts, aplicaciones/www/src/componentes/LineaTiempo.astro, aplicaciones/www/src/datosVisibles/indicadores.ts
Cambiar nombre de eje Y y en el valor en línea de tiempo según el tipo de datos.
=> 🐛 Cambiar nombre eje Y

aplicaciones/www/src/componentes/Encabezado.astro, aplicaciones/www/src/componentes/Linea.ts, aplicaciones/www/src/componentes/LineaTiempo.astro, aplicaciones/www/src/datosVisibles/indicadores.ts, aplicaciones/www/src/pages/[ya]/[indicador].astro
=> 🐛 Corregir eje Y de línea de tiempo

aplicaciones/www/src/componentes/FichaTecnica.astro, aplicaciones/www/src/componentes/Menu.astro, aplicaciones/www/src/componentes/PropuestaIndicador.astro, aplicaciones/www/src/pages/[ya]/[indicador].astro, aplicaciones/www/src/pages/datos.astro
Agregar fichas técnicas a página de datos y otras cositas ✧
=> ✨ Ficha técnica en datos

aplicaciones/www/src/componentes/Menu.astro, aplicaciones/www/src/pages/index.astro
=> ✨ Corrección de márgenes de menú y mapa bienvenida

aplicaciones/www/src/componentes/FichaTecnica.astro, aplicaciones/www/src/componentes/LineaTiempo.astro, aplicaciones/www/src/utilidades/constantes.ts
Arreglar umbral al cambiar tamaño de ventana.
=> 🥇 Arreglar umbral al cambiar tamaño de ventana

aplicaciones/www/src/componentes/LineaTiempo.astro, aplicaciones/www/src/componentes/PropuestaIndicador.astro, aplicaciones/www/src/scss/estilos.scss
Arreglar tamaño y cambiar orden de elementos en indicadores sugeridos.
=> 🐛 Arreglar indicadores suigeridos en pantallas

aplicaciones/www/src/componentes/DescripcionYa.astro, aplicaciones/www/src/componentes/Menu.astro, aplicaciones/www/src/pages/[ya]/[indicador].astro, aplicaciones/www/src/pages/[ya]/index.astro, aplicaciones/www/src/plantillas/Principal.astro
Arreglo de explicación de YAs en pantallas y celulares.
=> 🧋 Arreglo de explicación de YAs

aplicaciones/www/src/componentes/FichaTecnica.astro, aplicaciones/www/src/componentes/PropuestaIndicador.astro, aplicaciones/www/src/pages/[ya]/[indicador].astro, aplicaciones/www/src/pages/datos.astro, datosVisibles/ya7.ts
- Arreglar en celulares
- Mostrar sugerencias indicador sin datos
- Botón cerrar en ficha
- En página `datos` mostrar todos los indicadores
=> 🖌️ Arreglar estilos página Datos

aplicaciones/www/src/componentes/Mapa.astro, aplicaciones/www/src/utilidades/cerebro.ts, datosVisibles/ya5.ts
Leyenda en mapa para indicadores con categorías y un par de limpiezas de textos.
=> ✨ Leyenda en mapa para categorías y un par de limpiezas

aplicaciones/www/src/componentes/CategoriasRadiales.ts, aplicaciones/www/src/componentes/LineaTiempo.astro, aplicaciones/www/src/componentes/Mapa.astro, aplicaciones/www/src/scss/estilos.scss, aplicaciones/www/src/utilidades/cerebro.ts
Agregar leyendas de categorías y engordar gráficas de radar.
=> 👒 Agregar leyendas de categorías
